%% Dart Inspect - Mermaid Report
%% Directory: .
%% Options: --mermaid

classDiagram

  class DartClassInfo {
    List&lt;DartFieldInfo&gt; fields
    List&lt;String&gt; interfaces
    List&lt;String&gt; mixins
    String className
    String? superClass
    bool isAbstract
    bool isInterface
    bool isMixin
  }

  class DartFieldInfo {
    String name
    String type
  }

  class DartFileImports {
    List&lt;DartImportInfo&gt; imports
  }

  class DartImportInfo {
    String uri
    String? prefix
    bool isDeferred
  }

  class DartInspect {
    DartInspectOptions options
  }

  class DartInspectOptions {
    bool finalOnly
    bool markdown
    bool mermaid
    bool noClasses
    bool noFinal
    bool noImports
    bool noPrimitives
    bool privateOnly
  }

  class DartInspectReporter {
    DartInspectOptions options
    String directory
  }

  class ReportInfo {
    String? filePath
  }

  %% Relationships
  Comparable <|.. ReportInfo
  DartClassInfo --> DartFieldInfo
  DartFileImports --> DartImportInfo
  DartInspect --> DartInspectOptions
  DartInspectReporter --> DartInspectOptions
  ReportInfo <|-- DartClassInfo
  ReportInfo <|-- DartFileImports
  ReportInfo <|-- DartImportInfo

