%% Dart Inspect - Mermaid Report
%% Directory: .
%% Options: --mermaid, --sort-entries

classDiagram

  class DartClassInfo {
    String className
    List&lt;DartFieldInfo&gt; fields
    List&lt;String&gt; interfaces
    bool isAbstract
    bool isInterface
    bool isMixin
    List&lt;String&gt; mixins
    String? superClass
  }

  class DartFieldInfo {
    String name
    String type
  }

  class DartFileImports {
    List&lt;DartImportInfo&gt; imports
  }

  class DartImportInfo {
    bool isDeferred
    String? prefix
    String uri
  }

  class DartInspect {
    DartInspectOptions options
  }

  class DartInspectOptions {
    bool finalOnly
    bool markdown
    bool mermaid
    bool noClasses
    bool noEmptyClasses
    bool noFinal
    bool noImports
    bool noPrimitives
    bool privateOnly
    bool sortEntries
  }

  class DartInspectReporter {
    <<abstract>>
    String directory
    DartInspectOptions options
  }

  class DartInspectReporterMarkdown {
  }

  class DartInspectReporterMermaid {
  }

  class DartInspectReporterSimple {
  }

  class ReportInfo {
    <<abstract>>
    String? filePath
  }

  %% Relationships
  Comparable <|.. DartFieldInfo
  Comparable <|.. ReportInfo
  DartClassInfo --> DartFieldInfo
  DartFileImports --> DartImportInfo
  DartInspect --> DartInspectOptions
  DartInspectReporter --> DartInspectOptions
  DartInspectReporter <|-- DartInspectReporterMarkdown
  DartInspectReporter <|-- DartInspectReporterMermaid
  DartInspectReporter <|-- DartInspectReporterSimple
  ReportInfo <|-- DartClassInfo
  ReportInfo <|-- DartFileImports
  ReportInfo <|-- DartImportInfo

